####################################################
#              KHAI BAO CAC BIEN                   #
####################################################
Parameters:
  # Khai báo giá trị dãy địa chỉ ip cho public subnet
  PublicSubnetId:
    Description: Subnet ID of public subnet
    Type: String

  # Khai báo giá trị id của Private Route table
  PrivateRTId:
    Description: Route table ID for private subnet
    Type: String

  # Khai báo tên nhóm, bài lab thực hiện
  ProjectName:
    Description: name of group and lab
    Type: String


##########################################
#    LẤY CÁC TÀI NGUYÊN SAU KHI TẠO      #
########################################## 
Resources:
  # Tạo NAT Gateway và tạo route từ Private Routing Table tới NAT Gateway
  NATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: "vpc"
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-nat"
  RouteNATGateway:
    Type: AWS::EC2::Route
    DependsOn: NATGateway
    Properties:
      RouteTableId: !Ref PrivateRTId
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId: !Ref NATGateway