####################################################
#              KHAI BAO CAC BIEN                   #
####################################################
Parameters:
  # Khai báo vùng mạng vpc
  VpcCIDR:
    Description: IP range for vpc-group09
    Type: String

  # Khai báo dãy địa chỉ ip cho public subnet
  PublicSubnetCidr:
    Description: IP range for public subnet
    Type: String

  # Khai báo dãy địa chỉ ip cho private subnet
  PrivateSubnetCidr:
    Description: IP range for private subnet
    Type: String

  # Vùng triển khai vpc
  Zone:
    Description: zone that group09 deploy
    Type: String

  # Khai báo tên nhóm, bài lab thực hiện
  ProjectName:
    Description: name of group and lab
    Type: String


####################################################
#                  KHỞI TẠO RESOURCE               #
####################################################
Resources:
  # tạo vpc
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpc"


  # tạo internet gateway
  Igw: 
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: Name
          Value: !Sub "${ProjectName}-iwg"

  # gắn internet gateway vào vpc
  AttachVpcGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: Vpc
      InternetGatewayId:
        Ref: Igw

  # tạo public subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !Ref PublicSubnetCidr
      AvailabilityZone: !Ref Zone
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: !Sub "${ProjectName}-public-subnet"

  # tạo private subnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: Vpc
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Ref Zone
      Tags: 
        - Key: Name
          Value: !Sub "${ProjectName}-private-subnet"

##########################################
#    LẤY CÁC TÀI NGUYÊN SAU KHI TẠO      #
##########################################
Outputs:
  # Lấy giá trị VPC
  VpcId: 
    Value: !Ref Vpc
    Export: 
      Name: Group09VpcId

  # Lấy giá trị IWG
  IgwId: 
    Value: !Ref Igw
    Export: 
      Name: Group09IgwId
      
  # Lấy giá trị Public Subnet ID
  PublicSubnetId: 
    Value: !Ref PublicSubnet
    Export: 
      Name: Group09PublicSubnetId

  # Lấy giá trị Private Subnet ID
  PrivateSubnetId: 
    Value: !Ref PrivateSubnet
    Export:
      Name: Group09PrivateSubnetId 
          
  